# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='question',
            name='data_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='data_source_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='help_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='license_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='random_factor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
