# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20160916_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='region',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
