# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.CharField(choices=[('18_24', '18 - 24'), ('25_34', '25 - 34'), ('35_44', '35 - 44'), ('45_54', '45 - 54'), ('55_64', '55 - 64'), ('more_65', '65 or more')], default='18_24', help_text='I hereby certify that I am 18 years of age or older.', max_length=10, verbose_name='age range (years)'),
        ),
    ]
