# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20160802_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=150)),
                ('country_code', models.CharField(blank=True, max_length=6, unique=True)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('region_code', models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
